### ISSUE TITLE
reduce_model() failing

### ISSUE THREAD

**Issue by anniezou** [facebookresearch/fastText#1014]
I built fastText by cloning the git repository and running `pip install .` (as in https://github.com/facebookresearch/fastText/issues/1005 which looked like a similar issue).
When I first tried running `./reduce_model.py cc.en.300.bin 100` on the pre-trained English word vector, I got 

> AttributeError: module 'fasttext.util' has no attribute 'reduce_model'

I changed the `import fasttext.util` to `import import python.fasttext_module.fasttext.util.util as util` to get the command to run, which it did. However, I was expecting something like [what is described in the documentation](https://fasttext.cc/docs/en/crawl-vectors.html#adapt-the-dimension) but got the following error:

> Loading model
>
> Reducing matrix dimensions
> Traceback (most recent call last):
>   File "fastText/reduce_model.py", line 98, in <module>
>     main()
>   File "fastText/reduce_model.py", line 94, in main
>     'overwrite' if args.overwrite else 'strict'))
>   File "fastText/reduce_model.py", line 70, in command_reduce
>     util.reduce_model(ft, target_dim)
>   File "/n/fs/azouthesis/azouthesis2/fastText/python/fasttext_module/fasttext/util/util.py", line 125, in reduce_model
>     ft_model.set_matrices(inp_reduced, out_reduced)
> AttributeError: '_FastText' object has no attribute 'set_matrices'

Can someone help? Thank you!!

**Comment by kongzii** [comment]
Same problem here, did you manage to solve it somehow?

**Comment by anniezou** [comment]
Unfortunately not :(

**Comment by adalee2718** [comment]
You can handle it in the terminal, download the fasttext package on the terminal, and then use python in the terminal, and then follow the code given on the official website. This is how I handle it.

**Comment by koaning** [comment]
It is worth to mention that this issue persists on `fasttext==0.9.1`.

**Comment by juliandehne** [comment]
I have the same problem on the command line, too:

```
reduce_model.py ~/nltk_data/fasttext/cc.de.300.bin 100
Loading model
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
Reducing matrix dimensions
Killed
```
