### ISSUE TITLE
Installs fine via pip, but undefined symbol when trying to import

### ISSUE THREAD

**Issue by danielamassiceti** [facebookresearch/fastText#1073]
I create a new conda environment, and install fasttext via pip. It install fine, but then raises an error when I try to import the module in a python shell.

```
conda activate fasttext
(fasttext) ~/~$ pip install fasttext
Collecting fasttext
  Using cached fasttext-0.9.2.tar.gz (68 kB)
Requirement already satisfied: pybind11>=2.2 in ./Software/anaconda3/envs/fasttext/lib/python3.8/site-packages (from fasttext) (2.5.0)
Requirement already satisfied: setuptools>=0.7.0 in ./Software/anaconda3/envs/fasttext/lib/python3.8/site-packages (from fasttext) (46.4.0.post20200518)
Collecting numpy
  Downloading numpy-1.18.4-cp38-cp38-manylinux1_x86_64.whl (20.7 MB)
     |████████████████████████████████| 20.7 MB 6.2 MB/s
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... done
  Created wheel for fasttext: filename=fasttext-0.9.2-cp38-cp38-linux_x86_64.whl size=3020174 sha256=9f95e4c599d0fc88c4e4b236f02fef1b5be4c05793c446bd487f49e71d142fc3
  Stored in directory: /home/t-damass/.cache/pip/wheels/93/61/2a/c54711a91c418ba06ba195b1d78ff24fcaad8592f2a694ac94
Successfully built fasttext
Installing collected packages: numpy, fasttext
Successfully installed fasttext-0.9.2 numpy-1.18.4
(fasttext) ~/~$ python
Python 3.8.3 (default, May 19 2020, 18:47:26)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t-damass/Software/anaconda3/envs/fasttext/lib/python3.8/site-packages/fasttext/__init__.py", line 12, in <module>
    from .FastText import train_supervised
  File "/home/t-damass/Software/anaconda3/envs/fasttext/lib/python3.8/site-packages/fasttext/FastText.py", line 12, in <module>
    import fasttext_pybind as fasttext
ImportError: /home/t-damass/Software/anaconda3/envs/fasttext/lib/python3.8/site-packages/fasttext_pybind.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv120__si_class_type_infoE
```

**Comment by parulgarg123** [comment]
```
Successfully installed fasttext-0.9.2 numpy-1.18.4
8c85902eafe0:~ username$ python3
Python 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
>>>
```

I tried to reproduce the same on my mac but don't reproduced, It might be a platform specific. Have you tried to update the your setup tools, If not then remove fasttext and the update setup tools and then install package again. It might fix the issue.

**Comment by danielamassiceti** [comment]
As a temporary work-around, I installed PyTorch (1.5, via Conda, Linux 16.04) and by running:
```
import torch
import fasttext
```
it seems to import fine!
