### ISSUE TITLE
model can't be loaded by fasttext(python ) while the model trained by fasttext(cmake/make)

### ISSUE THREAD

**Issue by ucas010** [facebookresearch/fastText#1320]
hi,dear
```
>>> model_dim16=fasttext.load_model("fast3G.model.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/lib/python3.9/site-packages/fasttext/FastText.py", line 436, in load_model
    return _FastText(model_path=path)
  File "/data/lib/python3.9/site-packages/fasttext/FastText.py", line 94, in __init__
    self.f.loadModel(model_path)
ValueError: fast32G.model.bin cannot be opened for loading!
```
the fast3G.model.bin is trained by fasttext (cmake),
could you pls help me ?

**Comment by 520jefferson** [comment]
have you resolve the problem,  i also met this problem.
  File "lang_detect.py", line 4, in <module>
    model = fasttext.load_mode('lid.176.bin')
AttributeError: module 'fasttext' has no attribute 'load_mode'
