### ISSUE TITLE
Cannot load a pretrained model on Windows 

### ISSUE THREAD

**Issue by sauravm8** [facebookresearch/fastText#588]
I was trying to reload a previously trained FastText supervised model ( trained on RedHat ) on Windows. 

> fasstext PyPi build, 0.8.3

This is the error I am facing. 

```
Traceback (most recent call last):
  File "fasttext\fasttext.pyx", line 152, in fasttext.fasttext.load_model
RuntimeError: vector<T> too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PycharmProjects/fasttext/driver.py", line 3, in <module>
    fasttext.load_model("model.bin")
  File "fasttext\fasttext.pyx", line 154, in fasttext.fasttext.load_model
Exception: fastText: Cannot load model.bin due to C++ extension failed to allocate the memory
```

**Comment by sauravm8** [comment]
Solved, please use this link
https://www.cs.mcgill.ca/~mxia3/FastText-for-Windows/
