### ISSUE TITLE
pip install . doesn't work

### ISSUE THREAD

**Issue by NicolasFerland** [facebookresearch/fastText#617]
After doing this command in the Anaconda prompt:
(tensorflowgpu) D:\Python Scripts\fastText>pip install .

I'm getting this error.

Processing d:\python scripts\fasttext
Collecting pybind11>=2.2 (from fasttext==0.8.22)
  Using cached https://files.pythonhosted.org/packages/12/90/0f92a575dc60c8fba6d0c91d6b45abdb1058da9ebed40400cbcfad2ac0a7/pybind11-2.2.3-py2.py3-none-any.whl
Requirement already satisfied: setuptools>=0.7.0 in c:\users\nicol\anaconda3\envs\tensorflowgpu\lib\site-packages (from fasttext==0.8.22) (36.2.4)
Requirement already satisfied: numpy in c:\users\nicol\anaconda3\envs\tensorflowgpu\lib\site-packages (from fasttext==0.8.22) (1.15.0)
Exception:
Traceback (most recent call last):
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\site-packages\pip\_internal\resolve.py", line 261, in _resolve_one
    check_dist_requires_python(dist)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\site-packages\pip\_internal\utils\packaging.py", line 46, in check_dist_requires_python
    feed_parser.feed(metadata)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\email\feedparser.py", line 178, in feed
    self._input.push(data)
  File "C:\Users\nicol\Anaconda3\envs\tensorflowgpu\lib\email\feedparser.py", line 104, in push
    self._partial.write(data)
TypeError: string argument expected, got 'NoneType'

Does anyone know how to fix this issue? I'm using Anaconda with Python 3.5.5 on Windows 10.

**Comment by Celebio** [comment]
Hi @NicolasFerland ,
Can you please check again with the [latest version](https://pypi.org/project/fasttext/)?

Regards,
Onur
