### ISSUE TITLE
pip install ImportError: No module named 'Cython'

### ISSUE THREAD

**Issue by pecone** [facebookresearch/fastText#756]
when i install with pip install -r requirements.txt
i find error
likes need Cython first but it is before the fasttext

traceback like this

```
Step 1/7 : FROM python:3.5.2
 ---> 432d0c6d4d9a
Step 2/7 : COPY requirements.txt /tmp/requirements.txt
 ---> b2ee5cd7c7da
Removing intermediate container c330b41a3a22
Step 3/7 : RUN pip install -U pip && 	pip install -r /tmp/requirements.txt && 	rm /tmp/requirements.txt
 ---> Running in 5476fce0b5e7
Collecting pip
  Downloading https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.0.3
Collecting aiocache==0.10.1 (from -r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/61/18/7ddc03efbbe49b47d2b55ef8ece494c446090b9ae404fed39e4285eaf2e5/aiocache-0.10.1-py2.py3-none-any.whl
Collecting aiofiles==0.4.0 (from -r /tmp/requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/cf/f2/a67a23bc0bb61d88f82aa7fb84a2fb5f278becfbdc038c5cbb36c31feaf1/aiofiles-0.4.0-py3-none-any.whl
Collecting aiopg==0.15.0 (from -r /tmp/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/72/b0/c3599a35921b18741a01de7451ad829cc35c8a85ad366ad8a6bc859057ec/aiopg-0.15.0-py3-none-any.whl
Collecting aioredis==1.2.0 (from -r /tmp/requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/bc/2f/9ad85f5321f3f8604ae0f9b508f53f5f284fdb18b8095d1770f69e551a5e/aioredis-1.2.0-py3-none-any.whl (63kB)
Collecting appnope==0.1.0 (from -r /tmp/requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/87/a9/7985e6a53402f294c8f0e8eff3151a83f1fb901fa92909bb3ff29b4d22af/appnope-0.1.0-py2.py3-none-any.whl
Collecting async-timeout==2.0.1 (from -r /tmp/requirements.txt (line 6))
  Downloading https://files.pythonhosted.org/packages/1d/b9/213521db2918b5b7f7df333a33ea3d38ba70ba705d9db6c29f0343c213ea/async_timeout-2.0.1-py3-none-any.whl
Collecting asyncpg==0.18.3 (from -r /tmp/requirements.txt (line 7))
  Downloading https://files.pythonhosted.org/packages/30/b0/fcf5fcdeb8ce9ced0b18cd291f754e57c10b9b4121a2f06dd8180eb29577/asyncpg-0.18.3-cp35-cp35m-manylinux1_x86_64.whl (2.4MB)
Collecting backcall==0.1.0 (from -r /tmp/requirements.txt (line 8))
  Downloading https://files.pythonhosted.org/packages/84/71/c8ca4f5bb1e08401b916c68003acf0a0655df935d74d93bf3f3364b310e0/backcall-0.1.0.tar.gz
Collecting boto3==1.9.82 (from -r /tmp/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/4b/93/9c00e96d877bccccf988d4244c56261aef536682d3ad1ee38db5ae742d3e/boto3-1.9.82-py2.py3-none-any.whl (128kB)
Collecting botocore==1.12.82 (from -r /tmp/requirements.txt (line 10))
  Downloading https://files.pythonhosted.org/packages/ee/3a/2c1ef0f7d9f13db88a3b1475bfc0eafacfd9e5a622ecf8fb34ffb0c33fe3/botocore-1.12.82-py2.py3-none-any.whl (5.2MB)
Collecting certifi==2018.11.29 (from -r /tmp/requirements.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl (154kB)
Collecting chardet==3.0.4 (from -r /tmp/requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting curlify==2.1.1 (from -r /tmp/requirements.txt (line 13))
  Downloading https://files.pythonhosted.org/packages/65/85/21f3448fdb224aa6e41aced01b56d39302b963128ebfde9a082f79493840/curlify-2.1.1.tar.gz


Collecting Cython==0.29.3 (from -r /tmp/requirements.txt (line 14))
  Downloading https://files.pythonhosted.org/packages/2f/a3/ab68c915773126ef8d07d35b041d47a27ace46383b0733e1cca3bec89e74/Cython-0.29.3-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)


Collecting decorator==4.3.0 (from -r /tmp/requirements.txt (line 15))
  Downloading https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting docutils==0.14 (from -r /tmp/requirements.txt (line 16))
  Downloading https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl (543kB)
Collecting et-xmlfile==1.0.1 (from -r /tmp/requirements.txt (line 17))
  Downloading https://files.pythonhosted.org/packages/22/28/a99c42aea746e18382ad9fb36f64c1c1f04216f41797f2f0fa567da11388/et_xmlfile-1.0.1.tar.gz
Collecting facebook-business==3.2.5 (from -r /tmp/requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/e4/ea/66bf2eb3c0590b01ab2df2f5c456f6c1f7152e46835a93bdd33c5e7619f5/facebook_business-3.2.5.tar.gz (491kB)
Collecting future==0.17.1 (from -r /tmp/requirements.txt (line 19))
  Downloading https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz (829kB)
Collecting gunicorn==19.9.0 (from -r /tmp/requirements.txt (line 20))
  Downloading https://files.pythonhosted.org/packages/8c/da/b8dd8deb741bff556db53902d4706774c8e1e67265f69528c14c003644e6/gunicorn-19.9.0-py2.py3-none-any.whl (112kB)
Collecting hiredis==1.0.0 (from -r /tmp/requirements.txt (line 21))
  Downloading https://files.pythonhosted.org/packages/51/df/d2a08fb767247c0acea66255908e60cdeb4cd13cf71d42a1e2ca5803a1f8/hiredis-1.0.0-cp35-cp35m-manylinux1_x86_64.whl (49kB)
Collecting httptools==0.0.11 (from -r /tmp/requirements.txt (line 22))
  Downloading https://files.pythonhosted.org/packages/a3/75/40cdb732e8ef547d9f34ceb83c43ea7188c0ffb719ddc6a1ad160464292d/httptools-0.0.11.tar.gz (99kB)
Collecting idna==2.8 (from -r /tmp/requirements.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
Collecting ipdb==0.11 (from -r /tmp/requirements.txt (line 24))
  Downloading https://files.pythonhosted.org/packages/80/fe/4564de08f174f3846364b3add8426d14cebee228f741c27e702b2877e85b/ipdb-0.11.tar.gz
Collecting ipython==7.2.0 (from -r /tmp/requirements.txt (line 25))
  Downloading https://files.pythonhosted.org/packages/f0/b4/a9ea018c73a84ee6280b2e94a1a6af8d63e45903eac2da0640fa63bca4db/ipython-7.2.0-py3-none-any.whl (765kB)
Collecting ipython-genutils==0.2.0 (from -r /tmp/requirements.txt (line 26))
  Downloading https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting itsdangerous==1.1.0 (from -r /tmp/requirements.txt (line 27))
  Downloading https://files.pythonhosted.org/packages/76/ae/44b03b253d6fade317f32c24d100b3b35c2239807046a4c953c7b89fa49e/itsdangerous-1.1.0-py2.py3-none-any.whl
Collecting jdcal==1.4 (from -r /tmp/requirements.txt (line 28))
  Downloading https://files.pythonhosted.org/packages/a0/38/dcf83532480f25284f3ef13f8ed63e03c58a65c9d3ba2a6a894ed9497207/jdcal-1.4-py2.py3-none-any.whl
Collecting jedi==0.13.2 (from -r /tmp/requirements.txt (line 29))
  Downloading https://files.pythonhosted.org/packages/c2/bc/54d53f5bc4658380d0eca9055d72be4df45e5bfd91a4bac97da224a92553/jedi-0.13.2-py2.py3-none-any.whl (177kB)
Collecting jmespath==0.9.3 (from -r /tmp/requirements.txt (line 30))
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting msgpack==0.6.1 (from -r /tmp/requirements.txt (line 31))
  Downloading https://files.pythonhosted.org/packages/3d/44/4a8be4f56ab3c8fc58800c06b2d681d5622704746d094411f00e25300072/msgpack-0.6.1-cp35-cp35m-manylinux1_x86_64.whl (243kB)
Collecting multidict==4.5.2 (from -r /tmp/requirements.txt (line 32))
  Downloading https://files.pythonhosted.org/packages/0a/32/f0840e0305a79f8adbc606623a8a8d0196e931a07b946557fdff9df1196b/multidict-4.5.2-cp35-cp35m-manylinux1_x86_64.whl (304kB)
Collecting numpy==1.16.0 (from -r /tmp/requirements.txt (line 33))
  Downloading https://files.pythonhosted.org/packages/64/24/2e9c72f44cec8c872000d78c54230e40550c494647e352d1d06724cdaee6/numpy-1.16.0-cp35-cp35m-manylinux1_x86_64.whl (17.2MB)
Collecting openpyxl==2.5.12 (from -r /tmp/requirements.txt (line 34))
  Downloading https://files.pythonhosted.org/packages/08/8a/509eb6f58672288da9a5884e1cc7e90819bc8dbef501161c4b40a6a4e46b/openpyxl-2.5.12.tar.gz (173kB)
Collecting pandas==0.23.4 (from -r /tmp/requirements.txt (line 35))
  Downloading https://files.pythonhosted.org/packages/5d/d4/6e9c56a561f1d27407bf29318ca43f36ccaa289271b805a30034eb3a8ec4/pandas-0.23.4-cp35-cp35m-manylinux1_x86_64.whl (8.7MB)
Collecting parso==0.3.1 (from -r /tmp/requirements.txt (line 36))
  Downloading https://files.pythonhosted.org/packages/09/51/9c48a46334be50c13d25a3afe55fa05c445699304c5ad32619de953a2305/parso-0.3.1-py2.py3-none-any.whl (88kB)
Collecting peewee==3.7.0 (from -r /tmp/requirements.txt (line 37))
  Downloading https://files.pythonhosted.org/packages/51/a4/352594c746dae8f7090b740b61c5b7e84b072d8879ed23150cc4a9de3b6e/peewee-3.7.0.tar.gz (2.2MB)
Collecting peewee-async==0.6.0a0 (from -r /tmp/requirements.txt (line 38))
  Downloading https://files.pythonhosted.org/packages/d5/4f/8b34d9a9a255df3cc1e00a9dc99810ec09074c7dc0336fb369b9275ea899/peewee_async-0.6.0a0-py3-none-any.whl
Collecting pexpect==4.6.0 (from -r /tmp/requirements.txt (line 39))
  Downloading https://files.pythonhosted.org/packages/89/e6/b5a1de8b0cc4e07ca1b305a4fcc3f9806025c1b651ea302646341222f88b/pexpect-4.6.0-py2.py3-none-any.whl (57kB)
Collecting pickleshare==0.7.5 (from -r /tmp/requirements.txt (line 40))
  Downloading https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting prompt-toolkit==2.0.7 (from -r /tmp/requirements.txt (line 41))
  Downloading https://files.pythonhosted.org/packages/d1/e6/adb3be5576f5d27c6faa33f1e9fea8fe5dbd9351db12148de948507e352c/prompt_toolkit-2.0.7-py3-none-any.whl (338kB)
Collecting psycopg2==2.7.6.1 (from -r /tmp/requirements.txt (line 42))
  Downloading https://files.pythonhosted.org/packages/2d/fd/a02208785ced497f4412ab77e2d5b07386adcd4517b7c37e14990bcaf949/psycopg2-2.7.6.1-cp35-cp35m-manylinux1_x86_64.whl (2.7MB)
Collecting psycopg2-binary==2.7.6.1 (from -r /tmp/requirements.txt (line 43))
  Downloading https://files.pythonhosted.org/packages/f1/50/12c3134e6dc7295d92f97d12e625714c9d6cdd4740feebe81b27663fab18/psycopg2_binary-2.7.6.1-cp35-cp35m-manylinux1_x86_64.whl (2.7MB)
Collecting ptyprocess==0.6.0 (from -r /tmp/requirements.txt (line 44))
  Downloading https://files.pythonhosted.org/packages/d1/29/605c2cc68a9992d18dada28206eeada56ea4bd07a239669da41674648b6f/ptyprocess-0.6.0-py2.py3-none-any.whl
Collecting Pygments==2.3.1 (from -r /tmp/requirements.txt (line 45))
  Downloading https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl (849kB)
Collecting python-dateutil==2.7.5 (from -r /tmp/requirements.txt (line 46))
  Downloading https://files.pythonhosted.org/packages/74/68/d87d9b36af36f44254a8d512cbfc48369103a3b9e474be9bdfe536abfc45/python_dateutil-2.7.5-py2.py3-none-any.whl (225kB)
Collecting pytz==2018.9 (from -r /tmp/requirements.txt (line 47))
  Downloading https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl (510kB)
Collecting PyYAML==3.13 (from -r /tmp/requirements.txt (line 48))
  Downloading https://files.pythonhosted.org/packages/9e/a3/1d13970c3f36777c583f136c136f804d70f500168edc1edea6daa7200769/PyYAML-3.13.tar.gz (270kB)
Collecting requests==2.21.0 (from -r /tmp/requirements.txt (line 49))
  Downloading https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl (57kB)
Collecting s3transfer==0.1.13 (from -r /tmp/requirements.txt (line 50))
  Downloading https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
Collecting sanic==18.12.0 (from -r /tmp/requirements.txt (line 51))
  Downloading https://files.pythonhosted.org/packages/11/b1/96424ff7d7d53b45adda69ac5306b58f349d1b7a937430aeb397f61452be/sanic-18.12.0-py3-none-any.whl (52kB)
Collecting six==1.12.0 (from -r /tmp/requirements.txt (line 52))
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting traitlets==4.3.2 (from -r /tmp/requirements.txt (line 53))
  Downloading https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl (74kB)
Collecting ujson==1.35 (from -r /tmp/requirements.txt (line 54))
  Downloading https://files.pythonhosted.org/packages/16/c4/79f3409bc710559015464e5f49b9879430d8f87498ecdc335899732e5377/ujson-1.35.tar.gz (192kB)
Collecting urllib3==1.24.1 (from -r /tmp/requirements.txt (line 55))
  Downloading https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl (118kB)
Collecting uvloop==0.11.3 (from -r /tmp/requirements.txt (line 56))
  Downloading https://files.pythonhosted.org/packages/a3/1b/ce3e38f6d9b293aa64cbedf09aa09b55793fd7a2521c4e15323cb0ecfcab/uvloop-0.11.3-cp35-cp35m-manylinux1_x86_64.whl (3.6MB)
Collecting wcwidth==0.1.7 (from -r /tmp/requirements.txt (line 57))
  Downloading https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting websockets==6.0 (from -r /tmp/requirements.txt (line 58))
  Downloading https://files.pythonhosted.org/packages/8e/e8/8c959153f7e36258b410b90869c46a3f881a5a345539bf6b2a16049ea5f0/websockets-6.0-cp35-cp35m-manylinux1_x86_64.whl (86kB)
Collecting fasttext==0.8.3 (from -r /tmp/requirements.txt (line 59))
  Downloading https://files.pythonhosted.org/packages/a4/86/ff826211bc9e28d4c371668b30b4b2c38a09127e5e73017b1c0cd52f9dfa/fasttext-0.8.3.tar.gz (73kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-j21w6gis/fasttext/setup.py", line 3, in <module>
        from Cython.Build import cythonize
    ImportError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-j21w6gis/fasttext/
The command '/bin/sh -c pip install -U pip && 	pip install -r /tmp/requirements.txt && 	rm /tmp/requirements.txt' returned a non-zero code: 1
ERROR: Job failed: exit status 1
```

**Comment by Celebio** [comment]
Hi @pecone ,
Please install the github version as described [here](https://github.com/facebookresearch/fastText/tree/master/python#building-fasttext-for-python)

Best regards,
Onur

**Comment by Celebio** [comment]
Hi @pecone ,
Cython module was needed by the unofficial fasttext module. The official and unofficial modules are now merged, as described in [this blog post](https://fasttext.cc/blog/2019/06/25/blog-post.html).

Now you should be able to install the same python library either from github or pypi.

I am now closing this issue. Feel free to re-open it if you have any difficulty.

Best regards,
Onur
