### ISSUE TITLE
fasttext Windows Install Fail (python 3)

### ISSUE THREAD

**Issue by lhzst** [facebookresearch/fastText#832]
I was trying to install fasttext by using both pip3 and conda install, however the conda doesn't support windows OS for this particular library. And by using pip3, I ran into an error, can anybody help me out! Many thanks!! Error code showing below @Celebio Could you please kindly take a look of this error or is it possible to build it in conda for convenience thanks!:
 ##########
ERROR: Complete output from command 'c:\anaconda\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\szhang78\\AppData\\Local\\Temp\\2\\pip-install-81k_hkje\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\szhang78\AppData\Local\Temp\2\pip-record-pteey1kf\install-record.txt' --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\fasttext
    copying python\fasttext_module\fasttext\FastText.py -> build\lib.win-amd64-3.6\fasttext
    copying python\fasttext_module\fasttext\__init__.py -> build\lib.win-amd64-3.6\fasttext
    creating build\lib.win-amd64-3.6\fasttext\util
    copying python\fasttext_module\fasttext\util\util.py -> build\lib.win-amd64-3.6\fasttext\util
    copying python\fasttext_module\fasttext\util\__init__.py -> build\lib.win-amd64-3.6\fasttext\util
    creating build\lib.win-amd64-3.6\fasttext\tests
    copying python\fasttext_module\fasttext\tests\test_configurations.py -> build\lib.win-amd64-3.6\fasttext\tests
    copying python\fasttext_module\fasttext\tests\test_script.py -> build\lib.win-amd64-3.6\fasttext\tests
    copying python\fasttext_module\fasttext\tests\__init__.py -> build\lib.win-amd64-3.6\fasttext\tests
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\szhang78\AppData\Local\Temp\2\pip-install-81k_hkje\fasttext\setup.py", line 201, in <module>
        zip_safe=False,
      File "c:\anaconda\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\anaconda\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\anaconda\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\anaconda\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\anaconda\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\anaconda\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\anaconda\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\anaconda\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\anaconda\lib\site-packages\setuptools\command\build_ext.py", line 78, in run
        _build_ext.run(self)
      File "c:\anaconda\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
        _build_ext.build_ext.run(self)
      File "c:\anaconda\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "c:\anaconda\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "c:\anaconda\lib\distutils\cygwinccompiler.py", line 285, in __init__
        CygwinCCompiler.__init__ (self, verbose, dry_run, force)
      File "c:\anaconda\lib\distutils\cygwinccompiler.py", line 129, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'
    ----------------------------------------
ERROR: Command "'c:\anaconda\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\szhang78\\AppData\\Local\\Temp\\2\\pip-install-81k_hkje\\fasttext\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\szhang78\AppData\Local\Temp\2\pip-record-pteey1kf\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\szhang78\AppData\Local\Temp\2\pip-install-81k_hkje\fasttext\

**Comment by lhzst** [comment]
Btw, I installed a one called "fasttext-win" library, not sure if this one works the same with fasttext?

**Comment by Celebio** [comment]
Hi @lhzst ,
Thank you for your feedback.
The issue looks similar to [this one](https://github.com/pandas-dev/pandas/issues/18055) from pandas library.
Could you please try to install by retrieving the source code and running `python setup.py install` within your anaconda env? 

"fasttext-win" is not the same as the official fasttext. It looks like a port of the unofficial fasttext module to windows.

Regards,
Onur

**Comment by lhzst** [comment]
> retrieving
Hi Onur,
Thanks for your reply. I'm working on it now, will keep posted my status here.
Bests,
lhzst

**Comment by ageitgey** [comment]
If anyone still needs them, I posted unofficial pre-compiled Python 3.6, 3.7 and 3.8 wheel files for Windows python.org Python here: https://github.com/ageitgey/fastText-windows-binaries/releases/tag/v0.9.1

I also put the build instructions there if you want to re-build them yourself. In the latest version, it is pretty clean and easy to build on Windows.
