### ISSUE TITLE
Can't import fasttext after installed success

### ISSUE THREAD

**Issue by microvnn** [facebookresearch/fastText#904]
Collecting git+https://github.com/facebookresearch/fastText
  Cloning https://github.com/facebookresearch/fastText to c:\users\hungth12\appdata\local\temp\pip-req-build-88l_jup7
  Running command git clone -q https://github.com/facebookresearch/fastText 'C:\Users\hungth12\AppData\Local\Temp\pip-req-build-88l_jup7'
Requirement already satisfied: pybind11>=2.2 in c:\python37\lib\site-packages (from fasttext==0.9.1) (2.3.0)
Requirement already satisfied: setuptools>=0.7.0 in c:\python37\lib\site-packages (from fasttext==0.9.1) (41.0.1)
Requirement already satisfied: numpy in c:\python37\lib\site-packages (from fasttext==0.9.1) (1.16.1)
Building wheels for collected packages: fasttext
  Building wheel for fasttext (setup.py) ... done
  Created wheel for fasttext: filename=fasttext-0.9.1-cp37-cp37m-win_amd64.whl size=221024 sha256=d7881ce3ed27a6f1d523f431de3644f5f5d7ccaece8d381505bb16762a9a1076
  Stored in directory: C:\Users\hungth12\AppData\Local\Temp\pip-ephem-wheel-cache-mi7jzj_0\wheels\72\f6\b9\3a859d37e24c73635e6c6af085ad99829e8b2ab1bd965b15a9
Successfully built fasttext
Installing collected packages: fasttext
Successfully installed fasttext-0.9.1
----------------------------------------------
Python 3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fasttext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fasttext'
>>> import fasttext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'fasttext'
----------------------------------------------
os: window 10
Python 3.7.2
the problem import fasttext module. How to fixed this problem ?

**Comment by Celebio** [comment]
Hi @microvnn ,
Are you sure you are using the same env with the installation and the REPL?

One way you can do it is to use this:
```
python -m pip install git+https://github.com/facebookresearch/fastText
```
then
```
python
>>> import fasttext
```
Could you tell us what you get in this case?

Regards,
Onur

**Comment by Arjunsankarlal** [comment]
After successful installation, you could try `python setup.py develop` which would set all the paths and the configurations that are necessary. Let me know how it goes.

Best,
Arjun
