### ISSUE TITLE
UTF-8 string can not be opened for training

### ISSUE THREAD

**Issue by shabdakuhok** [facebookresearch/fastText#956]
I'm trying to make a fasttext word embedding for Bangla from my own corpus. 

```
for d in data:
        model = fasttext.train_unsupervised(d, dim = dimensions, epoch=n_epoch, minCount= min_count, thread= threads)
```
Here **data** is a python generator. in each iteration, **d** holds a single Bangla sentence as string type. After running the code, I am getting the following ValueError. 

```
Traceback (most recent call last):
  File "ft_embedding.py", line 33, in <module>
    model = ft_train(300, 35)
  File "ft_embedding.py", line 26, in ft_train
    model = fasttext.train_unsupervised(d, dim = dimensions, epoch=n_epoch, minCount= min_count, thread= threads)
  File "/home/ccse/.local/lib/python3.6/site-packages/fasttext/FastText.py", line 455, in train_unsupervised
    fasttext.train(ft.f, a)
ValueError: আমি মিথ্যার বেসাতি করি cannot be opened for training!
```
Is there something I'm doing wrong?

This is my code if you need it.
```
import fasttext
from os import path
from data_preprocess import load_pickle_files, tokenize_sentence, tokenize_word
import time

class DataProcessor(object):
    def __init__(self, filename):
        self.filename = filename
 
    def __iter__(self):
        articles_generator = load_pickle_files(self.filename)
        
        for an_article in articles_generator:
            sentence_generator = tokenize_sentence(an_article)
            for sentence in sentence_generator:
                data=[]
                for word in tokenize_word(sentence):
                    data.append(word)
                yield " ".join(data)
 
def ft_train(dimensions, n_epoch, min_count=2, threads=4):
    data = DataProcessor('input.conf')
    tic = time.time()
    for d in data:
        model = fasttext.train_unsupervised(d, dim = dimensions, epoch=n_epoch, minCount= min_count, thread= threads)
    toc = time.time()
    print(str((toc - tic)/60), " min")
    
    return model

if __name__ == "__main__":
    model = ft_train(300, 35)
    filename ="/home/ccse/FastText_embeddings/Models/ft_word_embeddings_35.model"
    model.save_model(filename)
    print(len(model.get_words))
```

**Comment by Celebio** [comment]
Hi @shabdakuhok ,
`train_unsupervised` expects a file name, not the training data string itself. You should first create a file with your data and then call `train_unsupervised`.

Best regards,
Onur

**Comment by AkibSadmanee** [comment]
@Celebio .. Thanks man!! I was dumb to miss that!!

**Comment by shabdakuhok** [comment]
@Celebio .. Thanks man!! I was dumb to miss a point like that!
